### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Mathildeuh** [Pseudow/SpigotTools#2]
Salut salut, j'aimerais bien avoir ton discord, celui sur ta page github ne fonctionne plus.

**Comment by Pseudow** [comment]
Salut mon discord est le suivant `Pseudow#1111`

**Comment by Mathildeuh** [comment]
Sa ne fonctionne pas

**Comment by Pseudow** [comment]
Salut, non c'est bien mon **discord**, si tu n'arrives pas a bien l'écrire je n'y peux rien.

![image](https://user-images.githubusercontent.com/64150196/181930396-27933e74-325c-43a8-a40e-7eb7f1b7af35.jpeg)

Au cas où voici mon **ID** discord: `567674487361765406`.

**Comment by Mathildeuh** [comment]
![image](https://user-images.githubusercontent.com/76065396/181933363-41782eea-315e-4545-9cea-d5e911384c0e.png)
Preuve que non, sa ne fonctionne pas.

**Comment by Mathildeuh** [comment]
<@567674487361765406>

![image](https://user-images.githubusercontent.com/76065396/181933409-c68fbe07-3df8-4b9b-b23e-8e843b33f066.png)

**Comment by Pseudow** [comment]
Dans ce cas j'ai sûrement dû te bloquer, quel est ton pseudo?

**Comment by Mathildeuh** [comment]
Mathilde#8888
